import { Inter } from "next/font/google";
import "./globals.css";
import MainContent from "@/components/MainContent";
import Layout from "@/components/Layout";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <MainContent>{children}</MainContent>
        </Layout>
      </body>
    </html>
  );
}
